# Generated by Django 3.2.4 on 2021-06-19 13:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_auto_20210619_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 19, 13, 32, 18, 505890, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='oraganizer_email',
            field=models.EmailField(default='test@test.com', max_length=254),
            preserve_default=False,
        ),
    ]
